# -*- coding: utf-8 -*-
"""Proyek Akhir Analisis Data dengan Pyhton

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XnnhJ2Ycc3Z9JvpYjpm8GKDiGzgePOo

# Proyek Analisis Data: Bike Sharing Analysis
- Nama:Sopyan
- Email:sopyanwae60@gmail.com
- Id Dicoding:sopyan_wae

## Menentukan Pertanyaan Bisnis

- pertanyaan 1 : Bagaimana variasi ketersediaan sepeda berdasarkan kondisi cuaca (weathersit) pada hari-hari tertentu? Apakah cuaca yang baik memengaruhi peningkatan penyewaan?
- pertanyaan 2 : Bagaimana hubungan antara suhu (temp) dan jumlah penyewaan sepeda harian? Apakah terdapat tren atau pola tertentu?
- pertanyaan 3 : Apakah ada perbedaan antara distribusi penyewaan sepeda antara weekend dan weekdays?
- pertanyaan 4 : Bagaimana kontribusi pengguna casual dan registered terhadap total penyewaan sepeda?

## Menyiapkan semua library yang dibuthkan
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#uploading dataset yang digunakan
day_df = pd.read_csv('day.csv')
hour_df = pd.read_csv('hour.csv')

#Hubungan Ketersediaan Sepeda Berdasrkan Kondisi Cuaca

plt.figure(figsize=(10, 5))

sns.barplot(
    y="cnt",
    x="weathersit",
    data=day_df,
    palette="viridis"
)
plt.title("Variasi Ketersediaan Sepeda Berdasarkan Kondisi Cuaca", loc="center", fontsize=15)
plt.ylabel("Jumlah Penyewaan")
plt.xlabel("Kondisi Cuaca")
plt.tick_params(axis='x', labelsize=12)
st.pyplot(plt)

#Hubungan antara suhu dan jumlah penyewaan sepeda harian

plt.figure(figsize=(10, 5))

sns.scatterplot(
    y="cnt",
    x="temp",
    data=day_df,
    palette="viridis"
)
plt.title("Hubungan Antara Suhu dan Jumlah Penyewaan Sepeda Harian", loc="center", fontsize=15)
plt.ylabel("Jumlah Penyewaan")
plt.xlabel("Suhu")
plt.tick_params(axis='x', labelsize=12)
st.pyplot(plt)

#Distribusi penyewaan sepeda pada weekend dan weekdays

plt.figure(figsize=(10, 5))

sns.barplot(
    y="cnt",
    x="holiday",
    data=day_df,
    palette="viridis"
)
plt.title("Distribusi penyewaan sepeda pada weekend daya weekdays", loc="center", fontsize=15)
plt.ylabel("Jumlah Penyewaan")
plt.xlabel("Weekend(1: Ya, 0: Tidak")
plt.tick_params(axis='x', labelsize=12)
st.pyplot(plt)

# Plotting kontribusi pengguna casual dan registered per tahun

plt.figure(figsize=(10, 5))
sns.barplot(data=day_df, x='weekday', y='cnt', hue='yr', palette='viridis')
plt.title('Kontribusi Pengguna Casual dan Registered Terhadap Total Penyewaan per Tahun')
plt.xlabel('Hari dalam Seminggu')
plt.ylabel('Jumlah Penyewaan')
st.pyplot(plt)

"""# Conlusion
**Conclution pertanyaan 1**: Berdasarkan barplot kondisi cuaca terhadap jumlah penyewaan dapat saya simpulkan menjadi:
- weathersit 1 : pada kondisi ini cuaca baik yang berpengaruh pada tingginya penyewaan sepeda.
-weathersit 2 dan 3 : pada kondisi ini cuaca lebih buruk sehingga terjadi penurunan penyewaan sepeda

**Conclution pertanyaan 2**: berdasarkan visualisasi berdasarkan scatterplot dapat disimpulkan bahwa semakin tinggi cuaca maka semakin tinggi pula jumlah penyewaan sepeda. Hal ini sejalan dengan conlusin pertanyaan 1.

**Conclution pertanyaan 3**: berdasrakan barplot menunujukan hasil bahwa tingkat penyewaan pada *weekdays* lebih tinggi dari pada *weekend*. Hal ini terjadi karena pada saat cuaca yang baik kecenderungan dari orang-orang untuk keluar rumah untuk menikmati keindahan alam.

**Conclution pertanyaan 4**: berdasarkan barplot dapat ditarik kesimpulan bahwa:
- pada tahun 2011 dan 2012 terlihat pengguna casual dan registered terhadap penyewaan sepeda cukup seragam.
- pengguna registered memberikan kontribusi lebih tinggi dibandingkan casual dalam penyewaan sepeda.
- karena tingginya pengguna registered dalam penyewaan sepeda, maka bisnis bisa meningkatkan jumlah pengguna registerednya untuk meningkatkan volume penyewaan ini.
