# -*- coding: utf-8 -*-
"""analisis_cuaca

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g22U4QxbgIYPfKw191BUbDg-fiZMpcjU

# Pertanyaan Bisnis

*   Bagaimana korelasi antara konsentrasi CO dan NO2 di kedua stasiun?
*  Bagaimana distribusi suhu udara di kedua lokasi selama periode waktu tersebut?
*  Bagaimana distribusi konsentrasi O3 di dua stasiun tersebut?
"""

import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

data_aot = pd.read_csv('PRSA_Data_Aotizhongxin_20130301-20170228.csv')
data_chang = pd.read_csv('PRSA_Data_Changping_20130301-20170228.csv')


"""### Pertanyaan 1: Bagaimana korelasi antara konsentrasi CO dan NO2 di kedua stasiun?"""

# Memilih kolom yang diperlukan (CO dan NO2)
selected_columns = ['CO', 'NO2']

# Membuat sub-dataframe untuk masing-masing stasiun
data_aot_selected = data_aot[selected_columns]
data_chang_selected = data_chang[selected_columns]

# Menggabungkan data kedua stasiun
merged_data = pd.concat([data_aot_selected, data_chang_selected], keys=['Aotizhongxin', 'Changping'], axis=1)

# Membuat heatmap untuk visualisasi korelasi
plt.figure(figsize=(10, 6))
sns.heatmap(merged_data.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Korelasi antara Konsentrasi CO dan NO2 di Aotizhongxin dan Changping')
st.pyplot(plt)

"""### Pertanyaan 2: Bagaimana distribusi suhu udara di kedua lokasi selama periode waktu tersebut?"""

print(data_aot.columns)
print(data_chang.columns)

assert 'year' in data_aot.columns
assert 'month' in data_aot.columns
assert 'day' in data_aot.columns
assert 'hour' in data_aot.columns

data_aot['date'] = pd.to_datetime(data_aot[['year', 'month', 'day', 'hour']])
data_chang['date'] = pd.to_datetime(data_chang[['year', 'month', 'day', 'hour']])

data_aot['date'] = pd.to_datetime(data_aot['date'])
data_chang['date'] = pd.to_datetime(data_chang['date'])

# Visualisasi distribusi suhu udara menggunakan histogram
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(data_aot['TEMP'].dropna(), kde=True, color='skyblue')
plt.title('Distribusi Suhu Udara di Aotizhongxin')
plt.xlabel('Suhu (°C)')
plt.ylabel('Frekuensi')

plt.subplot(1, 2, 2)
sns.histplot(data_chang['TEMP'].dropna(), kde=True, color='coral')
plt.title('Distribusi Suhu Udara di Changping')
plt.xlabel('Suhu (°C)')
plt.ylabel('Frekuensi')

plt.tight_layout()
st.pyplot(plt)

"""### Pertanyaan 3: Bagaimana distribusi konsentrasi O3 di dua stasiun tersebut?"""

# Visualisasi distribusi konsentrasi O3 menggunakan histogram
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(data_aot['O3'].dropna(), kde=True, color='skyblue')
plt.title('Distribusi Konsentrasi O3 di Aotizhongxin')
plt.xlabel('Konsentrasi O3')
plt.ylabel('Frekuensi')

plt.subplot(1, 2, 2)
sns.histplot(data_chang['O3'].dropna(), kde=True, color='coral')
plt.title('Distribusi Konsentrasi O3 di Changping')
plt.xlabel('Konsentrasi O3')
plt.ylabel('Frekuensi')

plt.tight_layout()
st.pyplot(plt)

"""# Conlusion

**Pertanyaan 1:** Berdasarkan visualisasi kita mendapatkan pemahaman bahwa:
- Terdapat korelasi positif antara konsentrasi CO dan NO2 di kedua stasiun. Ini menunjukkan bahwa ketika konsentrasi CO naik, konsentrasi NO2 juga cenderung naik, dan sebaliknya.
- Korelasi tersebut dapat bervariasi antara dua stasiun, dengan perbedaan warna pada heatmap menunjukkan tingkat korelasi yang berbeda.

**Pertanyaan 2:** Berdasarkan visualisasi kita mendapatkan pemahaman bahwa:
- Distribusi suhu udara di Aotizhongxin dan Changping menunjukkan perbedaan pola suhu di kedua lokasi.
- Aotizhongxin: Suhu udara cenderung memiliki distribusi yang lebih tinggi di beberapa rentang tertentu
- Changping: Distribusi suhu udara di Changping mungkin memiliki - variasi yang lebih luas atau berbeda pola distribusi

**Pertanyaan 3:** Berdasarkan visualisasi kita mendapatkan pemahaman bahwa:
- Terdapat perbedaan dalam distribusi konsentrasi O3 antara stasiun Aotizhongxin dan Changping.
- Aotizhongxin: Mungkin menunjukkan pola atau tren tertentu dalam konsentrasi O3.
- Changping: Distribusi konsentrasi O3 di Changping mungkin memiliki karakteristik yang berbeda.
"""